# Generated by Django 3.1.3 on 2020-11-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_content',
            field=models.CharField(default='something went wrong :(', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_title',
            field=models.CharField(max_length=20),
        ),
    ]
